import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'], // required
  weight: ['400', '700'], // optional
});

import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
